### ISSUE TITLE
Undocumented dependency: `currify`

### ISSUE THREAD

**Issue by stevendesu** [coderaiser/fs-readdir-sync-with-file-types#1]
I just installed this polyfill to fix a script I had that wasn't working properly in Windows and started getting errors:

    Error: Cannot find module `currify/legacy`

Likely this just needs to be added to the package.json `dependencies` list

**Comment by coderaiser** [comment]
Thank you, landed in [v1.0.5](https://github.com/coderaiser/fs-readdir-sync-with-file-types/releases/tag/v1.0.5) 🎉
